---

- name: Deploy to {{ project_name }} production server
  hosts: production
  remote_user: {{ ansible_user }}
  gather_facts: false
  become: yes

  vars_files:
    - env_vars/protected.yml
    - env_vars/production.yml
    - env_vars/base.yml

  roles:
    - deploy
