---

- name: ensure server_user exists
  become: true
  user:
    name: "{{ server_user }}"
    group: "{{ server_user }}"
    state: present

- name: Update/upgrade apt-get
  become: true
  apt:
    update_cache: yes
    upgrade: dist

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ bash_ssl }}"

- name: Install system packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ system_packages }}"

- name: Upgrade pip
  become: true
  pip:
    name: pip
    extra_args: "--upgrade"

- name: install virtualenv
  become: true
  pip:
    name: "{{ item }}"
  with_items: "{{ virtualenv_pkgs }}"

- name: add virtualenv to bash
  lineinfile:
    dest: ~/.bashrc
    line: "export WORKON_HOME=/venv"
    insertafter: EOF

- name: add virtualenvwrapper to bash
  lineinfile:
    dest: ~/.bashrc
    line: "source /usr/local/bin/virtualenvwrapper.sh"
    insertafter: EOF

- name: Create ssh folder
  file:
    path: /.ssh
    state: directory

- name: Upload github ssh key
  copy:
    src: "{{ git_host_ssh }}"
    dest: /.ssh/github
    mode: 0600