---

#- name: install uwsgi systemwide
#  become: true
#  apt:
#    name: "{{ item }}"
#    state: latest
#  with_items:
#    - uwsgi
#    - uwsgi-plugin-python

- name: pip install uwsgi
  become: true
  pip:
    name: uwsgi
    state: latest

- name: Create uwsgi log folder
  file:
    path: "{{ application_log_dir }}/uwsgi"
    state: directory

- name: Make sure uwsgi log file exists
  file:
    path: "{{ application_log_dir }}/uwsgi/{{ conf_name }}.log"
    group: "{{ server_user }}"
    owner: "{{ server_user }}"
    state: touch

- name: Create uwsgi socket folder
  file:
    path: "{{ sock_dir }}"
    group: "{{ server_user }}"
    owner: "{{ server_user }}"
    state: directory

- name: Create uwsgi site folder
  file:
    path: /etc/uwsgi/apps-available
    state: directory

- name: Create uwsgi site folder
  file:
    path: /etc/uwsgi/apps-enabled
    state: directory

- name: Copy uwsgi site ini file
  template:
    src: uwsgi_site.ini.j2
    dest: "/etc/uwsgi/apps-available/{{ conf_name }}.ini"
  notify: restart uwsgi

- name: Enable site uwsgi app
  file:
    src: "/etc/uwsgi/apps-available/{{ conf_name }}.ini "
    dest: "/etc/uwsgi/apps-enabled/{{ conf_name }}.ini"
    state: link
    force: yes
  notify: restart uwsgi

- name: Copy uwsgi site conf file
  template:
    src: uwsgi.conf.j2
    dest: "/etc/init/uwsgi.conf"
  notify: restart uwsgi

- name: Make sure uwsgi is running (and runs on boot)
  command: echo "web services restarted"
  notify: start uwsgi

# see gunicorn tasks/vars
# create uwsgi.conf to launch emperor mode??? see templates