---

- name: Install Nginx
  apt:
    name: nginx
    update_cache: "{{ update_apt_cache }}"
    state: installed

- name: Create Nginx folder
  file:
    path: /etc/nginx/sites-available
    state: directory

- name: Create Nginx folder
  file:
    path: /etc/nginx/sites-enabled
    state: directory

#- name: Copy the SSL certificate to the remote server
#  copy: content="{{ ssl_crt }}" dest={{ ssl_dest_dir }}/{{ application_name }}.crt
#  notify: restart nginx
#
#- name: Copy the SSL private key to the remote server
#  copy: content="{{ ssl_key }}" dest={{ ssl_dest_dir }}/{{ application_name }}.key
#  notify: restart nginx

- name: Create the Nginx configuration file
  template:
    src: nginx.j2
    dest: "/etc/nginx/sites-available/{{ conf_name }}"
    backup: yes

- name: check conf syntax
  become: true
  command: service nginx configtest
  notify: restart nginx

- name: Ensure that the default site is disabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Symlink site conf to sites-enabled
  file:
    src: "/etc/nginx/sites-available/{{ conf_name }}"
    dest: "/etc/nginx/sites-enabled/{{ conf_name }}"
    state: link
    force: yes
  notify: restart nginx

- name: Ensure Nginx service is started
  service:
    name: nginx
    state: started
    enabled: yes
  notify: restart uwsgi